#!/bin/bash
# run-expr

usage()
{
    echo "usage: run-expr [-f] [-c count] <experiment name> [results-dir]" >&2;
}

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    usage;
    exit 2;
fi

force=0;
count=3;
while getopts hfc: opt; do
	case $opt in
	    f) force=1;;
        h) usage;;
	    c) count=$OPTARG;;
	    *) echo "error: invalid option given." >&2; usage;;
	esac
done
shift $[ OPTIND - 1 ]


expName="$1";
resultsDir=".";
if [ $# -eq 2 ]; then
    resultsDir="$2";
fi
mkdir -p "$resultsDir/$expName";
for ((i = 1; i <= $count; i++)); do 
    # Add a check to not overwrite currently existing results?
    outfile="$resultsDir/$expName/$i.out"
    if [ "$force" -eq 1 ] && [ -f "$outfile"  ]; then
        echo "warning: '$outfile' already exists; skipping." >&2;
    else
        alps_main "$expName" "$resultsDir/$expName/$i" | tee "$outfile"
    fi
done
