#!/bin/bash
# run-expr-all

usage()
{
   echo "usage: run-expr-all [-c count] <results-name>" >&2;
}
if [ $# -ne 1 ]; then
    usage;
    exit 2;
fi

count=1;
while getopts hfc: opt; do
	case $opt in
	    f) force=1;;
        h) usage;;
	    c) count=$OPTARG;;
	    *) echo "error: invalid option given." >&2; usage;;
	esac
done
shift $[ OPTIND - 1 ]

for exp in An Bn Ap Bp Ao Bo; do
    run-expr -c $count $exp "$1"
done
