#!/bin/bash
# mstrip

function usage()
{
    echo "usage: mstrip [-hp] <input>" >&2;
    exit 2;
}

paste=0;
#skip=0;
while getopts hps opt; do
	case $opt in
	    p) paste=1;;
#        s) skip=1;;
        h) usage;;
	    *) echo "error: invalid option given." >&2; usage;;
	esac
done
shift $[ OPTIND - 1 ]

pscript='if (/\:m\:/) { s/^\:m\://; print; }';


if [ $paste -eq 1 ]; then
    pbpaste | perl -ne "$pscript"
else
    perl -ne "$pscript" "$@"
fi

