#!/bin/bash
# run-expr

function usage()
{
    echo "usage: run-expr [-Dfp] [-i id] [-n nice] [-c count] [-d results-dir] [-F fitness-type] <experiment-name> <task-index> <lobotomise>" >&2;
}


fullargs="$*";
force=0;
parallel=0;
count=1;
num=1;
nice=0;
resultsDir=".";
fitnessType=2;
runType=0; # STANDARD_RUN
alps_main="alps-like";
#alps_main="alps_main";
while getopts phfc:i:d:F:n:P:D opt; do
	case $opt in
	    f) force=1;;
        p) parallel=1;;
        P) parallel=$OPTARG;;
        h) usage;;
        d) resultsDir="$OPTARG";;
        i) num=$OPTARG;;
	    c) count=$OPTARG;;
        F) fitnessType=$OPTARG;;
	    n) nice=$OPTARG;;
        D) runType=1;; #DEBUG_RUN
	    *) echo "error: invalid option given." >&2; usage;;
	esac
done
shift $[ OPTIND - 1 ]

if [ $# -ne 3 ]; then
    usage;
    exit 2;
fi

function echo_alps()
{

    echo "$@" "$alps_main -f -T $runType -F $fitnessType $expName $targetIndex $lobotomise $dir ";
}

function run_alps()
{
    if true || [ $nice -eq 0 ]; then
        $alps_main -f -T "$runType" -F "$fitnessType" "$expName" "$targetIndex" "$lobotomise" "$dir";
    else
        nice -n $nice $alps_main -f -T "$runType" -F "$fitnessType" "$expName" "$targetIndex" "$lobotomise" "$dir";
    fi
}
    
expName="$1";
targetIndex="$2";
lobotomise="$3";

for ((i = $num; i < ($num + $count); i++)); do 
    dir="$resultsDir/$expName-t$targetIndex-l$lobotomise/r$i";
    errorlog="$resultsDir/error.log";
    mkdir -p "$dir";

    # Add a check to not overwrite currently existing results?
    outfile="$dir/output.txt";
    if [ "$force" -eq 0 ] && [ -f "$outfile"  ]; then
        echo "warning: '$outfile' already exists; skipping." >&2;
    else

        if [ $parallel -eq 0 ]; then
            echo -n "Teeing: ";
            echo_alps -n;
            echo "2>> $errorlog | tee $outfile";
            if ! run_alps  2>> "$errorlog" | tee "$outfile"; then
                echo "error: alps_main failed with exit code ${PIPESTATUS}" >&2;
                exit 1;
            fi
        elif [ $parallel -eq 1 ]; then
            echo -n "Spawning: "
            echo_alps -n
            echo "2>> $errorlog > $outfile &"
            run_alps 2>> "$errorlog" > "$outfile" &
        elif [ $parallel -eq 2 ]; then
            echo -n "Running: "
            echo_alps -n 
            echo "2>> $errorlog > $outfile"
            run_alps 2>> "$errorlog" > "$outfile" 
            if [ "$KILL_PPID" == "yes" ]; then
                kill -SIGUSR1 $PPID
                echo "Finished: run-expr $fullargs";
            fi
        else
            echo "error: invalid parallel value $parallel" >&2;
            exit 2;
        fi
    fi
done

if [ $parallel -eq 1 ]; then
    echo "run-expr: Waiting for processes to die.";
    wait;
fi
