#!/bin/bash
# run-expr-all

usage()
{
   echo "usage: run-expr-all [-hfp] [-P parallel-code] [-i id] [-n nice] [-c count] [-F fitness-type] <results-name>" >&2;
   exit 2;
}

parallel=0;
force=0;
num=1;
count=1;
fitnessType=0;
nice=0;
options="";
while getopts hfpc:i:F:n:P: opt; do
	case $opt in
	    f) force=1;options="-f ";;
        P) parallel=$OPTARG;;
	    p) parallel=1;;
        h) usage;;
	    c) count=$OPTARG;;
        i) num=$OPTARG;;
        F) fitnessType=$OPTARG;;
	    n) nice=$OPTARG;;
	    *) echo "error: invalid option given." >&2; usage;;
	esac
done
shift $[ OPTIND - 1 ]

if [ $# -ne 1 ]; then
    usage;
fi

for ((i = $num; i < ($num + $count); i++)); do 
    for target in 1; do # 2 3 4; do 
	    for lobotomise in 0 1; do
            for exp in An Bn Ap Bp Ao Bo; do
                if [ $parallel -eq 0 ]; then
		            if ! run-expr $options -F $fitnessType -i $i -c 1 -d "$1" $exp $target $lobotomise; then
                        echo "error: run-expr exited with error code ${PIPESTATUS}" >&2;
                        exit 1;
		            fi
                elif [ $parallel -eq 1 ]; then
                    run-expr $options -P 2 -F $fitnessType -i $i -c 1 -d "$1" $exp $target $lobotomise &
                elif [ $parallel -eq 2 ]; then
                    echo "run-expr $options -P 2 -F $fitnessType -i $i -c 1 -d $1 $exp $target $lobotomise"
                else 
                    echo "error: unknown parallel code: $parallel" >&2;
                    exit 3;
                fi
            done
	    done
    done
    if [ $parallel -eq 1 ]; then
        echo "run-expr-all: Waiting for jobs to finish for run $i before starting new ones."
        wait
    fi
done
